user_index:
    path:     /{initial}
    defaults: { _controller: "SophrologieBundle:User:index", initial: all }

user_show:
    path:     /{id}/show
    defaults: { _controller: "SophrologieBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "SophrologieBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "SophrologieBundle:User:edit" }
    methods:  [GET, POST]

user_historic:
    path:     /{id}/historic
    defaults: { _controller: "SophrologieBundle:User:historic" }
    methods:  GET

user_confirm:
    path:     /{id}/confirm
    defaults: { _controller: "SophrologieBundle:User:confirm" }
    methods:  GET
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "SophrologieBundle:User:delete" }
    methods:  GET
