<?php

namespace SophrologieBundle\Repository;

/**
 * AppointmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
