<?php

namespace SophrologieBundle\Repository;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByTime(){

        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->orderBy("s.time")
        ;
        $query = $queryBuilder->getQuery();
        $result = $query->getResult();
        return $result;

    }
}
