<?php

namespace SophrologieBundle\Repository;

use SophrologieBundle\Entity\User;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllPastByUser(User $user){
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->where('s.user = :user')
            ->andWhere('s.enabled = :true')
            ->setParameter('user', $user)
            ->setParameter('true', 0)
        ;
        $query = $queryBuilder->getQuery();
        $result = $query->getResult();
        return $result;

    }
    public function findAllCurrentByUser(User $user){
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->where('s.user = :user')
            ->andWhere('s.enabled = :true')
            ->setParameter('user', $user)
            ->setParameter('true', 1)
        ;
        $query = $queryBuilder->getQuery();
        $result = $query->getResult();
        return $result;

    }


}
