<?php

namespace SophrologieBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUsersOrderByNameAndFirstname(){
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->orderBy('s.name, s.firstname');
        $query = $queryBuilder->getQuery();
        $result = $query->getResult();
        return $result;

    }

    public function findAllUsersOrderByNameAndFirstnameStartingByLetter($initial){
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->where('s.name LIKE :initial')
            ->orderBy('s.name, s.firstname')
            ->setParameter('initial', $initial. '%');
        $query = $queryBuilder->getQuery();
        $result = $query->getResult();
        return $result;

    }

    public function countAllUserByUsername($username){
        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder
            ->select('COUNT(s)')
            ->where('s.username LIKE :username')
            ->setParameter('username', $username . '%');
        $query = $queryBuilder->getQuery();
        $result = $query->getSingleScalarResult();
        return $result;

    }

}
