SophrologieBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: SophrologieBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        firstname:
            type: string
            length: '50'
        mail:
            type: string
            length: 255
        phonenumber:
            type: string
            length: 255
            nullable: yes
        commentary:
            type: text
            nullable: yes
        username:
            type: string
            length: 255
            unique: yes
            nullable: yes
        password:
            type: string
            length: 255
            nullable: yes
    lifecycleCallbacks: {  }
    manyToMany:
        appointments:
            targetEntity: Appointment
            inversedBy: users
            cascade: [ persist ]
        roles:
            targetEntity: Role
            inversedBy: users
    oneToMany:
        themes:
            targetEntity: Theme
            mappedBy: user
            cascade: [ persist]

